#默认使用配置
spring:
  main:
    banner-mode: "off"
  profiles:
    active: dev
  webflux:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

#公共配置与profiles选择无关
mybatis:
  type-aliases-package: com.smartaddress.demo.po
  mapper-locations: classpath*:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  path: ${user.home}/logs/
  config: classpath:logging-config.xml

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true

pagehelper:
  help-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql;pageNum=pageNum;pageSize=pageSize


freemarker:
  allow-request-override: false
  cache: true
  check-template-location: true
  charset: UTF-8
  content-type: text/html
  expose-request-attributes: false
  expose-session-attributes: false
  expose-spring-macro-helpers: false
  suffix: .ftl
  template-loader-path: classpath:/templates/

jwt:
  enable: true
  secret-key: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  validity-milliseconds: 36000